packages:
  - .

ignoredBuiltDependencies:
  - baileys

link-workspace-packages: true

onlyBuiltDependencies:
  - '@ffmpeg-installer/darwin-arm64'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - prisma
  - protobufjs
  - sharp

prefer-workspace-packages: true
